linters:
  ErbSafety:
    enabled: false
#    better_html_config: .better-html.yml
  FinalNewline:
    enabled: true
  Rubocop:
    enabled: true
    only:
      - Style/StringLiterals
    rubocop_config:
      inherit_from:
        - .rubocop.yml
