version: 2.1
orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@3.0.1
  slack: circleci/slack@3.4.2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
      - image: circleci/postgres:11.6
    environment:
      RAILS_ENV: test
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Initialize DB
          command: bundle exec rails db:create db:schema:load --trace
      #      - node/install-packages:
      #          pkg-manager: yarn
      # - ruby/rubocop-check
      - ruby/rspec-test
      - slack/status
workflows:
  version: 2
  make_it_so:
    jobs:
      - test
