default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tranquility_development

test:
  <<: *default
  database: tranquility_test

production:
  <<: *default
  database: tranquility_production
  username: tranquility
  password: <%= ENV['TRANQUILITY_DATABASE_PASSWORD'] %>