default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>

development:
  <<: *default
  database: tranquility_development

test:
  <<: *default
  database: tranquility_test
  host: 127.0.0.1
